dist: trusty

language: php

php:
  - 7.4
  - nightly
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

sudo: false

install:
  - composer install

script:
  - composer test
